### ISSUE TITLE
Crash on unbalanced stack with non-V variable

### ISSUE THREAD

**Issue by ckaestne** [ckaestne/vbc#1]
The algorithm for the unbalanced stack seems to assume that all stack values are `V`s, but does not seem to realize that some wrapped values are subsequently used as plain values. The following example crashes, because it tries to invoke the `toString()` method on a `V<Integer>`.

``` scala
test("unbalanced non-V value") {
    method(
      Block(InstrNEW("java/lang/Integer"), InstrDUP(), InstrICONST(3), InstrINVOKESPECIAL("java/lang/Integer", "<init>", "(I)V", false)),
      Block(InstrINVOKEVIRTUAL("java/lang/Integer", "toString", "()Ljava/lang/String;", false)),
      Block(InstrDBGIPrint()),
      Block(InstrRETURNVoid())
    )
  }
```

Technically wrapping the value into a `V` seems unnecessary here (the constructor may crash conditionally, but that would not produce multiple values, just a more narrow context; which is the reason why we need two blocks in the first place). We can lift it, but then we also need to lift all calls on it subsequently.

@chupanw

**Comment by chupanw** [comment]
Resolved in pull request #2
